# Generated by Django 4.2.7 on 2023-12-09 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("petlistings", "0014_alter_petlisting_months_old_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.TextField()),
                ("weight", models.FloatField()),
                (
                    "petlisting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="petlistings.petlisting",
                    ),
                ),
            ],
        ),
    ]
