# Generated by Django 4.2.7 on 2023-11-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_application_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
