# Generated by Django 4.2.6 on 2023-11-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0002_petlisting_shelter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petlisting',
            old_name='creation_date',
            new_name='listing_date',
        ),
        migrations.RenameField(
            model_name='petlisting',
            old_name='weight',
            new_name='size',
        ),
        migrations.AddField(
            model_name='petlisting',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted'), ('pending', 'Pending'), ('withdrawn', 'Withdrawn')], default='available', max_length=9),
        ),
    ]
