# Generated by Django 4.2.6 on 2023-11-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0004_listingimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='listing',
        ),
    ]
