# Generated by Django 4.2.6 on 2023-11-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0006_listingimage_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listingimages/'),
        ),
    ]
