# Generated by Django 4.2.6 on 2023-11-13 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petlistings', '0007_alter_listingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='petlistings.petlisting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='shelter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
