# Generated by Django 4.2.6 on 2023-11-14 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0009_remove_petlisting_age_petlisting_months_old_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='months_old',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11.0)]),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='years_old',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
