APPLICATION_QUESTIONS = {
    "Your address:": 1,
    "City:": 2, 
    "Postal Code:": 3,
    "Phone number:": 4,
    "Email:": 5,
    "Are you 21 years of age and over?:": 6,
    "List all members of your household including number of children and their ages. Who will be primarily responsible for the care of this pet?": 7,
    "Do you live in a house, apartment, condominium or townhouse?:": 8,
    "Do you own or rent your home?:": 9,
    "How long have you lived at your current address (in years)?:": 10,
    "Do you have plans to move from your current address within the next 3 months?:": 11,
    "Do you have a securely fenced in yard?:": 12,
    "Do you have a pool?:": 13,
    "Why have you chosen this particular pet?:": 14,
    "Please explain your reasons for wanting to adopt a pet:": 15,
    "For whom are you adopting a pet? For you or for someone else? (If for someone else, who?):": 16,
    "What experience do you have as a pet owner? If you have been a pet owner, please tell us about your previous pets:": 17,
    "How long has it been since you've had a pet in your life?:": 18,
    "Do you have dog training experience? And if so, what training do you have?:": 19,
    "Do you currently have any pets?:": 20,
    "Is any member of your family allergic to dogs?:": 21,
    "Are you applying for a young puppy (6 months old or younger)?": 22,
}